# Generated by Django 5.2.17 on 2026-08-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_department_id_alter_userrecord_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='georef_ground_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='georef_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='georef_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='georef_north_offset_deg',
            field=models.FloatField(default=0.0),
        ),
    ]
