# Generated by Django 5.2.17 on 2026-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_building_georef_ground_z_building_georef_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='surface_ref_m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
