# Generated by Django 5.2.17 on 2026-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_building_surface_ref_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroimodel',
            name='frame_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paroimodel',
            name='frame_u',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
