# Generated by Django 5.2.17 on 2026-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paroimodel_frame_fraction_paroimodel_frame_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroimodel',
            name='is_glazing',
            field=models.BooleanField(default=False),
        ),
    ]
