# Generated by Django 5.2.17 on 2026-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paroimodel_is_glazing'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='suggested_debit_vent_m3h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='suggested_eta_recup_vent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
